### ISSUE TITLE
webui 서버 포트 수정이 가능할까요?

### ISSUE THREAD

**Issue by XEROHN** [SeongSikChae/PowerManagerConfig#4]
시놀로지에 도커로 올려서 해볼려고 하고있습니다만,
이미 80포트나 443포트는 다른 곳에서 이미 사용 중이여서 접속을 위해 webui 포트를 임의의 포트로 돌려놨는데,
config 프로그램에서 webui url을 입력할 때 포트를 같이 입력해주어도 ssl 인증에러가 발생해서 질문드립니당

config 프로그램 실행 시 parameter로 넘겨주는 --web_server_addr 에서,
https://192.168.219.200:16443
이런식으로 줬는데, 포트가 443포트로 고정된 상태인지 궁금합니다.

--clientCertificate C.p12 (프로그램과 같은경로에 배치)
--clientCertificatePassword 1234
SSL 인증서 관련한 parameter도 올바르게 주었다고 생각합니다만, 혹시나해서 작성합니다.

인증서 사용해서 브라우저에서 포트입력하여 접속 시 webui페이지에서 기기삭제, 수정, 등록도 가능한걸로 보아
현재 webui쪽에는 문제가 없다고 판단됩니다.

아래는 발생한 에러입니다.

Unhandled exception. System.AggregateException: One or more errors occurred. (The SSL connection could not be established, see inner exception.)
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at PowerManagerConfig.Program.MqttAuthAdd(Configuration config, String userId, String mac, String verify, String mqttKey) in D:\Git\PowerManager\PowerManagerConfig\Program.cs:line 605
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at PowerManagerConfig.Program.SendV3(Socket socket, Configuration config) in D:\Git\PowerManager\PowerManagerConfig\Program.cs:line 406
   at PowerManagerConfig.Program.<>c.<Main>b__0_0(Configuration config) in D:\Git\PowerManager\PowerManagerConfig\Program.cs:line 50
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at PowerManagerConfig.Program.Main(String[] args) in D:\Git\PowerManager\PowerManagerConfig\Program.cs:line 22

**Comment by SeongSikChae** [comment]
포트는 고정되어있지 않습니다 입력 되는 파라메터 URL을 그대로 사용하는 것이고

에러메시지를 보면 "The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch" 이것을 보아서는 인증서 유효성 검사에서 오류난 것으로 판단되며 서버인증서 또는 클라이언트 인증서가 유효하지 않은 상태로 판단됩니다.

**Comment by XEROHN** [comment]
감사합니다. 다시 처음부터 진행해보겠습니다.
일단 현재 인증서에 문제점으로 보이는 것이라면,
크롬브라우저에서 접속하기 전에 "css서버 보안 인증서에 주체 대체 이름(SAN)이 지정되어 있지 않아~"
라는 오류가 떠있고, 인증서를 사용해서 접속하면 주소창에 "주의요함" 이라는 문구가 떠있는데,
인증서가 잘못된 것 같습니다.

**Comment by XEROHN** [comment]
아 펌웨어 ~.34버전은 진행이 안되는군요. ㅠㅠ
일단은 중단해야겠습니다.
 ㅡ 그리고 인증서 사용해서 크롬브라우저로 webui 접속은 되는데, 주소창에 주의요함 이라는게 떠있습니다.
크롬에서 강제로 접속하기 전에 표시된 문제점을 보면 
"css서버 보안 인증서에 주체 대체 이름(SAN)이 지정되어 있지 않아~"
라는게 떠있는데, 인증서 작성이 잘못된 것이겠죠?

**Comment by XEROHN** [comment]
혹시 mqtt 서버 주소가 다른 것도 문제가 있을까요?
HAOS(192.168.219.190)에서 mqtt 브로커로 mqtt서버를 만들어놨는데,
css 서버가 돌아가는거는 시놀로지(192.168.219.200) 도커라서 ip가 다르긴 합니다.

**Comment by XEROHN** [comment]
mqtt 서버와 dawonai 서버의 ip주소가 각기 달라서 생기는 인증서 오류였던 것 같습니다.
같은 ip주소로 맞춰주니까 인증서 오류가 발생하지 않네요.
