### ISSUE TITLE
최신 릴리즈버전 abf32ce6에서 에러가 발생합니다.

### ISSUE THREAD

**Issue by HanXHoon** [SeongSikChae/PowerManagerConfig#5]
안녕하세요, 프로그램 정말 잘 사용하고 있습니다.
감사드립니다.

최신버전 "abf32ce6" 사용 시 에러가 발생하며 프로그램이 중단됩니다.
AIPM 앱에서 기기 등록이 확인되며, 공유기 연결까지 되는거 보니 최종 마무리 단에서 뭔가 문제가 생기는 듯 합니다.

이전버전 "077c09da" 사용 시에는 파워쉘에서 에러는 발생하지않고 mqtt key까지 뱉습니다만 연결은 안됩니다.

천천히 다시 확인해보니, 컨피그 프로그램의 문제라기보단 서버단의 문제인 것 같습니다.
PowerManagerServer의 페이지에서 /api/auth/add 요청에서 아무런 응답이 오지않아 발생하는 듯 합니다.

서버 액세스 로그확인했을 때에는 정상적으로 주는 것 같은데, 왜 다시 회신이 안올까요.

## Config 실행 에러메시지
```
Unhandled exception. System.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at PowerManagerConfig.IRestService.RestService.GetMqttAuthAsync(Configuration config, MqttAuthRequest req) in D:\Git\PowerManagerV2\PowerManagerConfig\PowerManagerConfig\IRestService.cs:line 120
   at PowerManagerConfig.IConfigrator.ConfigratorV3.ConfigureAsync() in D:\Git\PowerManagerV2\PowerManagerConfig\PowerManagerConfig\IConfigrator.cs:line 351
   at PowerManagerConfig.Program.<>c.<<Main>b__0_1>d.MoveNext() in D:\Git\PowerManagerV2\PowerManagerConfig\PowerManagerConfig\Program.cs:line 44
--- End of stack trace from previous location ---
   at CommandLine.ParserResultExtensions.WithParsedAsync[T](ParserResult`1 result, Func`2 action)
   at PowerManagerConfig.Program.Main(String[] args) in D:\Git\PowerManagerV2\PowerManagerConfig\PowerManagerConfig\Program.cs:line 10
   at PowerManagerConfig.Program.<Main>(String[] args)
```

## 서버 액세스 로그
[삭제] 라고 되어있는 것은 제가 임의로 지운 것입니다.
데이터는 정상입니다.
192.168.0.220 : 서버가 돌아가고 있는 IP
192.168.0.191 : DNS서버 중계용 라우터
```
2024-02-12 00:37:54.705 +09:00 [Information] [PowerManagerServer.RequestLoggingMiddleware.Invoke:0] 192.168.0.191:1913
 => 192.168.0.220:18443 POST /api/v1/devices/register/create 200 {"account":{"user_id":"[삭제]"},"device":{"mac":"[삭제]","model_id":"B540_W","company":"DAWONDNS","lati":"[삭제]","long":"[삭제]","verify":"true"}} Host=dwapi.dawonai.com,Content-Type=application/json,Content-Length=181,X-HIT-Version=1.0,
2024-02-12 00:37:54.710 +09:00 [Information] [PowerManagerServer.RequestLoggingMiddleware.Invoke:0] 192.168.0.191:1913
 => 192.168.0.220:18443 POST /Error/Index 404  
```

**Comment by HanXHoon** [comment]
아무래도 인증서에 문제가 있었던 듯 합니다.

서버 이전하면서 처음부터 다시 스마트플러그 설정을 했는데, ip주소 입력해서 파워매니저 서버 웹페이지에 접근하려하니까
Firefox브라우저는 접속이 되는데, bing브라우저랑 chrome브라우저가 ERR_SSL_KEY_USAGE_INCOMPATIBLE 에러가 나면서 접속이 안되더라구요.

차근차근 처음부터 다시한게 몇 번은 해본 거 같은데, 혹시나 해서 인증서 문제인가... 생각이들어
한참 이전버전의 "343f5a57" 사용해봤는데 연결이 됐습니다.

"343f5a57"에 파라미터에 client certificate관련이 없는데,
웹페이지에 기기 등록과정이 생략돼서 에러가 발생하지 않아 스마트플러그와 통신이 완료되었고, 그래서 연결이 된 것 같습니다.

ERR_SSL_KEY_USAGE_INCOMPATIBLE 에러가 발생하는 거는 크로미움 엔진쪽이 뭔가 패치를 하면서 개인 인증서가 적용이 안되나보네요.

**Comment by SeongSikChae** [comment]
인증서를 크로미움 엔진에 맞게 다시 생성을 해야할 것 같습니다.

**Comment by SeongSikChae** [comment]
release: https://github.com/SeongSikChae/PowerManagerConfig/releases/tag/v1.0.2
